name: Better Interview Book

on:
  push:
    branches:
    - main
    pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        npm i

